language: php

php:
  - 5.6

before_script:
  - composer selfupdate --no-progress
  - composer install --no-interaction --prefer-dist --no-progress 
  - mkdir tests/_temp

script:
  - vendor/bin/run-tests tests/

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

